// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lsvasredqhbbperwzyog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzdmFzcmVkcWhiYnBlcnd6eW9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ2OTUzOTAsImV4cCI6MjA5MDI3MTM5MH0.LzqR7_ZpbrN4_6pdAqu3lM1NH-RnGAW0sd_TVEv2Mjk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});